

export const inventory = {
    acura: ['ar54'],
    bmw: ['b68'],
    chrysler: ['cs56'],
    ford: ['f556'],
    gmc: ['g55'],
    honda: ['ho68'],
    hyundai: ['hy86'],
    infiniti: ['i865'],
    kia: ['k66'],
    mazada: ['ma686'],
    mercedes: ['me53'],
    mini: ['mi28'],
    mitsubishi: ['ms545'],
    nissan: ['n586'],
    porsche: ['po56'],
    subaru: ['su5'],
    toyota: ['tl863'],
    vw: ['vw6'],
    volvo: ['vo745'],
};

/* export const inventory = {
    acura: [],
    bmw: [],
    chrysler: [],
    ford: [],
    gmc: [],
    honda: [],
    hyundai: [],
    infiniti: [],
    kia: [],
    mazada: [],
    mercedes: [],
    mini: [],
    mitsubishi: [],
    nissan: [],
    porsche: [],
    subaru: [],
    toyota: [],
    vw: [],
    volvo: [],
}; */
